program AIONE;

uses
  Vcl.Forms,
  uTraducao,
  uDM in 'uniBasico\uDM.pas' {DM: TDataModule},
  uPrincipal in 'uniBasico\uPrincipal.pas' {FrmPrincipal},
  uMenCad in 'uniBasico\uMenCad.pas' {FrmMenCad},
  uLibFarm in 'uniAuxilia\uLibFarm.pas',
  uInfoIni in 'uniAuxilia\uInfoIni.pas' {FrmInfoIni},
  uBusca in 'uniAuxilia\uBusca.pas' {FrmBusca},
  uConfgIni in 'uniAuxilia\uConfgIni.pas',
  uLogSistema in 'uniAuxilia\uLogSistema.pas',
  uProdutos in 'uniProduto\uProdutos.pas' {FrmProdutos},
  uProdutoCad in 'uniProduto\uProdutoCad.pas' {FrmProdCad},
  uProdEAN in 'uniProduto\uProdEAN.pas' {FrmProdEAN},
  uProSubs in 'uniProduto\uProSubs.pas' {FrmProSubs},
  uTipoProSer in 'uniProduto\uTipoProSer.pas' {FrmTipProSer},
  uGrupos in 'uniProduto\uGrupos.pas' {FrmGrupos},
  uGruposSub in 'uniProduto\uGruposSub.pas' {FrmGruposSub},
  uGrupoPre in 'uniProduto\uGrupoPre.pas' {FrmGrupoPre},
  uUnidades in 'uniProduto\uUnidades.pas' {FrmUnidades},
  uPessoas in 'uniPessoa\uPessoas.pas' {FrmPessoas},
  uPessoasCad in 'uniPessoa\uPessoasCad.pas' {FrmPesCad},
  uPessAutor in 'uniPessoa\uPessAutor.pas' {FrmPesAutor},
  uPessConv in 'uniPessoa\uPessConv.pas' {FrmPesConv},
  uPessConta in 'uniPessoa\uPessConta.pas' {FrmPesConta},
  uPessTraba in 'uniPessoa\uPessTraba.pas' {FrmPesTraba},
  uPessUsoCont in 'uniPessoa\uPessUsoCont.pas' {FrmPesUCon},
  uPessCred in 'uniPessoa\uPessCred.pas' {FrmPesCred},
  uPessObser in 'uniPessoa\uPessObser.pas' {FrmPesObser},
  uPessBanc in 'uniPessoa\uPessBanc.pas' {FrmPesBanc},
  uConvenio in 'uniConve\uConvenio.pas' {FrmConvenios},
  uDescontoCad in 'uniDesco\uDescontoCad.pas' {FrmDesCad},
  uPromocao in 'uniPromo\uPromocao.pas' {FrmPromocao},
  uPromFil in 'uniPromo\uPromFil.pas' {FrmPromFil},
  uPromGru in 'uniPromo\uPromGru.pas' {FrmPromGru},
  uPromSub in 'uniPromo\uPromSub.pas' {FrmPromSub},
  uPromFab in 'uniPromo\uPromFab.pas' {FrmPromFab},
  uPromCon in 'uniPromo\uPromCon.pas' {FrmPromCon},
  uPromFpg in 'uniPromo\uPromFpg.pas' {FrmPromFpg},
  uPromEco in 'uniPromo\uPromEco.pas' {FrmPromEco},
  uPromoFiltros in 'uniPromo\uPromoFiltros.pas' {FrmPromFiltros},
  uPromocaoCad in 'uniPromo\uPromocaoCad.pas' {FrmPromCad},
  uMigracao in 'uniAuxilia\uMigracao.pas',
  uPromPro in 'uniPromo\uPromPro.pas' {FrmPromPro},
  WeatherAPI in 'uniAuxilia\WeatherAPI.pas',
  uFatores in 'uniAuxilia\uFatores.pas',
  uIAGeral in 'uniAuxilia\uIAGeral.pas',
  uArea51 in 'uniAuxilia\uArea51.pas' {FrmArea51},
  uIAPromo in 'uniPromo\uIAPromo.pas',
  uPromProCad in 'uniPromo\uPromProCad.pas' {FrmPromoCadPro},
  uPromPgr in 'uniPromo\uPromPgr.pas' {FrmPromPgr},
  uPromPgrPro in 'uniPromo\uPromPgrPro.pas' {FrmPromPgrPro},
  uPessNego in 'uniPessoa\uPessNego.pas' {FrmPesNego},
  uConvenioCad in 'uniConve\uConvenioCad.pas' {FrmConvCad},
  uABCFarma in 'uniAuxilia\uABCFarma.pas',
  uAutoUpdate in 'uniAuxilia\uAutoUpdate.pas' {FrmAutoUpdate},
  uSubstancia in 'uniProduto\uSubstancia.pas' {FrmSubstancia},
  uBuscaPro in 'uniProduto\uBuscaPro.pas' {FrmBuscaPro},
  uBuscaPes in 'uniPessoa\uBuscaPes.pas' {FrmBuscaPes},
  uConsultFiscal in 'uniAuxilia\ConsultFiscal\uConsultFiscal.pas',
  uConsultJSONParser in 'uniAuxilia\ConsultFiscal\uConsultJSONParser.pas',
  uWait in 'uniAuxilia\uWait.pas' {FrmWait},
  uValidaFis in 'uniProduto\uValidaFis.pas' {FrmValidaFis},
  uConvGru in 'uniConve\uConvGru.pas' {FrmConLimGru},
  uConvCli in 'uniConve\uConvCli.pas' {FrmConPesAti},
  uBuscaCon in 'uniConve\uBuscaCon.pas' {FrmBuscaCon},
  uBuscaDes in 'uniDesco\uBuscaDes.pas' {FrmBuscaDes},
  uBuscaProm in 'uniPromo\uBuscaProm.pas' {FrmBuscaProm},
  uMenFin in 'uniFinan\uMenFin.pas' {FrmMenFin},
  uTitulosCad in 'uniFinan\uTitulosCad.pas' {FrmTitCad},
  uBuscaTit in 'uniFinan\uBuscaTit.pas' {FrmBusTit},
  uEntCodBar in 'uniFinan\uEntCodBar.pas' {FrmTitCodBar},
  uMultTit in 'uniFinan\uMultTit.pas' {FrmMulTit},
  uPlaConta in 'uniFinan\uPlaConta.pas' {FrmPlaCon},
  uNatFina in 'uniFinan\uNatFina.pas' {FrmNatFin},
  uTitulosBai in 'uniFinan\uTitulosBai.pas' {FrmTitBai},
  uTituloEst in 'uniFinan\uTituloEst.pas' {FrmTitEst},
  uRatValor in 'uniFinan\uRatValor.pas' {FrmRatVlr},
  uBuscaPlc in 'uniFinan\uBuscaPlc.pas' {FrmBuscaPlc},
  uBancos in 'uniFinan\uBancos.pas' {FrmBancos},
  uBoletos in 'uniFinan\uBoletos.pas',
  uMsgEnvBol in 'uniFinan\uMsgEnvBol.pas' {FrmMsgEnvBol},
  uCartao in 'uniFinan\uCartao.pas' {FrmCartao},
  uBanCartao in 'uniFinan\uBanCartao.pas' {FrmBanCart},
  uRatValorTemp in 'uniFinan\uRatValorTemp.pas' {FrmRatVlrTemp},
  uValorRatTemp in 'uniFinan\uValorRatTemp.pas' {FrmVlrRatTemp},
  uCaixaProc in 'uniFinan\uCaixaProc.pas' {FrmProcCX},
  uPixConf in 'uniFinan\uPixConf.pas' {FrmPixConf},
  uCofre in 'uniFinan\uCofre.pas' {FrmCofre},
  uCxConf in 'uniFinan\uCxConf.pas' {FrmCxConf},
  uCxConfIte in 'uniFinan\uCxConfIte.pas' {FrmCxConfIte},
  uGeraBol in 'uniFinan\uGeraBol.pas' {FrmGeraBol},
  uRetTitBco in 'uniFinan\uRetTitBco.pas' {FrmRetTitBco},
  uPromCli in 'uniPromo\uPromCli.pas' {FrmPromCli},
  uDescPgr in 'uniDesco\uDescPgr.pas' {FrmDescPgr},
  uConvFil in 'uniConve\uConvFil.pas' {FrmConFilial},
  uConvBol in 'uniConve\uConvBol.pas' {FrmConBoleto},
  uMostraMsg in 'uniAuxilia\uMostraMsg.pas' {FrmMostraMsg},
  uMenu in 'uniAuxilia\uMenu.pas' {FrmMenu},
  uCompras in 'uniCompra\uCompras.pas' {FrmCompras},
  uCompraCad in 'uniCompra\uCompraCad.pas' {FrmCompraCad},
  uCompAbe in 'uniCompra\uCompAbe.pas' {FrmCompAbe},
  uCompIte in 'uniCompra\uCompIte.pas' {FrmCompIte},
  uCompCriIA in 'uniCompra\uCompCriIA.pas' {FrmCompCIA},
  uCompIteFil in 'uniCompra\uCompIteFil.pas' {FrmCompFil},
  uCompAddIt in 'uniCompra\uCompAddIt.pas' {FrmCompAdd},
  uEntraLote in 'uniCompra\Recebimento\uEntraLote.pas' {FrmEntLotes},
  uNotasPendEnt in 'uniCompra\Recebimento\uNotasPendEnt.pas' {FrmNotasPendEnt},
  uEntradaLote in 'uniCompra\Recebimento\uEntradaLote.pas' {FrmEntradaLote},
  uCompRec in 'uniCompra\Recebimento\uCompRec.pas' {FrmCompEnt},
  uManiDest in 'uniCompra\Recebimento\uManiDest.pas' {FrmManiDest},
  uJustManiDest in 'uniCompra\Recebimento\uJustManiDest.pas' {FrmJustManiDest},
  uCompTipRec in 'uniCompra\Recebimento\uCompTipRec.pas' {FrmCompTipRec},
  uConfRecEnt in 'uniCompra\Recebimento\uConfRecEnt.pas' {FrmConfRecEnt},
  uLocEsto in 'uniProduto\uLocEsto.pas' {FrmLocEsto},
  uBuscaLoc in 'uniProduto\uBuscaLoc.pas' {FrmBuscaLoc},
  uAssProLoc in 'uniProduto\uAssProLoc.pas' {FrmAssProLoc},
  uVendas in 'uniVendas\uVendas.pas' {FrmVendas},
  uTaxaEntr in 'uniVendas\uTaxaEntr.pas' {FrmTaxaEntr},
  uTaxCidBai in 'uniVendas\uTaxCidBai.pas' {FrmTaxCidBai},
  uCidBairro in 'uniVendas\uCidBairro.pas' {FrmCidBairro},
  uTaxaFilial in 'uniVendas\uTaxaFilial.pas' {FrmTaxaFilial},
  uConEsto in 'uniVendas\uConEsto.pas' {FrmConEsto},
  uDevVenda in 'uniVendas\uDevVenda.pas' {FrmDevVenda},
  uBusVenda in 'uniVendas\uBusVenda.pas' {FrmBusVenda},
  uVenProm in 'uniVendas\uVenProm.pas' {FrmVenProm},
  uArqConvenio in 'uniVendas\uArqConvenio.pas',
  uFecVenda in 'uniVendas\uFecVenda.pas' {FrmFecVenda},
  uVenAgenda in 'uniVendas\uVenAgenda.pas' {FrmAgeVenda},
  uEdVendedor in 'uniVendas\uEdVendedor.pas' {FrmEdtVend},
  uBuscaSemDB in 'uniAuxilia\uBuscaSemDB.pas' {FrmBuscaSemDB},
  uBuscaVT in 'uniAuxilia\uBuscaVT.pas' {FrmBuscaVT},
  uAbreCx in 'uniCaixa\uAbreCx.pas' {FrmAbreCx},
  uCaixa in 'uniCaixa\uCaixa.pas' {FrmCaixa},
  uPendente in 'uniCaixa\uPendente.pas' {FrmCxPend},
  uFechaPG in 'uniCaixa\uFechaPG.pas' {FrmFechaPG},
  uArqPedido in 'uniVendas\uArqPedido.pas',
  IABase in 'uniAuxilia\IABase.pas',
  uConfig in 'uniAuxilia\uConfig.pas' {FrmConfig},
  uTipoReceita in 'uniAuxilia\uTipoReceita.pas' {FrmTipoReceita},
  uComissao in 'uniComi\uComissao.pas' {FrmComissao},
  uBuscaCom in 'uniComi\uBuscaCom.pas' {FrmBuscaCom},
  uComiCad in 'uniComi\uComiCad.pas' {FrmComiCad},
  uComiGru in 'uniComi\uComiGru.pas' {FrmComiGru},
  uComiSub in 'uniComi\uComiSub.pas' {FrmComiSub},
  uComiFab in 'uniComi\uComiFab.pas' {FrmComiFab},
  uComiPro in 'uniComi\uComiPro.pas' {FrmComiPro},
  uComiFil in 'uniComi\uComiFil.pas' {FrmComiFil},
  uComiVen in 'uniComi\uComiVen.pas' {FrmComiVen},
  uComiPgr in 'uniComi\uComiPgr.pas' {FrmComiPgr},
  uDescPro in 'uniDesco\uDescPro.pas' {FrmDescPro},
  uDescFab in 'uniDesco\uDescFab.pas' {FrmDescFab},
  uDescGru in 'uniDesco\uDescGru.pas' {FrmDescGru},
  uDescSub in 'uniDesco\uDescSub.pas' {FrmDescSub},
  uDescConv in 'uniDesco\uDescConv.pas' {FrmDescCon},
  uDescCli in 'uniDesco\uDescCli.pas' {FrmDescCli},
  uKitProd in 'uniProduto\uKitProd.pas' {FrmKitProduto},
  uKitBus in 'uniProduto\uKitBus.pas' {FrmKitBus},
  uSupSanCx in 'uniCaixa\uSupSanCx.pas' {FrmSupSanCx},
  uSupSanBus in 'uniCaixa\uSupSanBus.pas' {FrmSupSanBus},
  uVendasAddIt in 'uniCaixa\uVendasAddIt.pas' {FrmVendaAdd},
  uCaixaLan in 'uniCaixa\uCaixaLan.pas' {FrmCaixaLan},
  uBuscaCDS in 'uniAuxilia\uBuscaCDS.pas' {FrmBuscaCDS},
  uDescontos in 'uniDesco\uDescontos.pas' {FrmDescontos},
  uDescFil in 'uniDesco\uDescFil.pas' {FrmDescFil},
  uVendasInc in 'uniSNGPC\uVendasInc.pas' {FrmVendasInc},
  uVenda in 'uniSNGPC\uVenda.pas' {FrmSNVen},
  uTransmite in 'uniSNGPC\uTransmite.pas' {FrmTransmite},
  uSNGPC in 'uniSNGPC\uSNGPC.pas' {FrmSNGPC},
  uSNEstoque in 'uniSNGPC\uSNEstoque.pas' {FrmSNEstoq},
  uQtdEstLote in 'uniSNGPC\uQtdEstLote.pas' {FrmQtdEstLote},
  uPerdasInc in 'uniSNGPC\uPerdasInc.pas' {FrmPerdasInc},
  uPerdas in 'uniSNGPC\uPerdas.pas' {FrmPerdas},
  uInveIni in 'uniSNGPC\uInveIni.pas' {FrmInveIni},
  uComTraInc in 'uniSNGPC\uComTraInc.pas' {FrmComTraInc},
  uComTra in 'uniSNGPC\uComTra.pas' {FrmComTra},
  uBuscaProdPerda in 'uniSNGPC\uBuscaProdPerda.pas' {FrmBuscaProdPerda},
  uBuscaInv in 'uniSNGPC\uBuscaInv.pas' {FrmBuscaInv},
  uAlteraDataVenci in 'uniSNGPC\uAlteraDataVenci.pas' {FrmAlteraDataVenci},
  uBuscaProd in 'uniAuxilia\uBuscaProd.pas' {FrmBuscaProd},
  uTabConfigRecCtl in 'uniVendas\uTabConfigRecCtl.pas',
  uTabPromProg in 'uniVendas\uTabPromProg.pas',
  uTabDescProg in 'uniVendas\uTabDescProg.pas',
  uVenUniLevPag in 'uniVendas\uVenUniLevPag.pas' {FrmVenUniLevPag},
  uWaitForm in 'uniAuxilia\uWaitForm.pas',
  uConst in 'uniAuxilia\uConst.pas',
  MySQLSchemaSync in 'uniAuxilia\MySQLSchemaSync.pas',
  uFiscal in 'uniFatura\uFiscal.pas' {FrmFiscal},
  uNFEmitida in 'uniFatura\uNFEmitida.pas' {FrmNFEmit},
  uCertificados in 'uniFatura\uCertificados.pas',
  uNFEven in 'uniFatura\uNFEven.pas' {FrmNFEven},
  uNFEvenObs in 'uniFatura\uNFEvenObs.pas' {FrmNFEvenObs},
  uNFEvenTra in 'uniFatura\uNFEvenTra.pas' {FrmNFEvenTra},
  uNFEvenRef in 'uniFatura\uNFEvenRef.pas' {FrmNFEvenRef},
  uShadowForm in 'uniAuxilia\uShadowForm.pas',
  uCompRecTit in 'uniCompra\Recebimento\uCompRecTit.pas' {FrmCompRecTit},
  uCompRecRat in 'uniCompra\Recebimento\uCompRecRat.pas' {FrmCompRecRat},
  uCompRecPre in 'uniCompra\Recebimento\uCompRecPre.pas' {FrmCompRecPre},
  uComDet in 'uniCompra\uComDet.pas' {FrmComDet},
  uMenComp in 'uniCompra\uMenComp.pas' {FrmMenComp},
  uIAVendaCli in 'uniVendas\IAVenda\uIAVendaCli.pas' {FrmIAVenCli},
  uIAVendaPro in 'uniVendas\IAVenda\uIAVendaPro.pas' {FrmIAVenPro},
  uMetaBus in 'uniVendas\Metas\uMetaBus.pas' {FrmMetaBus},
  uMetaGru in 'uniVendas\Metas\uMetaGru.pas' {FrmMetaGru},
  uMetaPro in 'uniVendas\Metas\uMetaPro.pas' {FrmMetaPro},
  uMetaFab in 'uniVendas\Metas\uMetaFab.pas' {FrmMetaFab},
  uMetaFil in 'uniVendas\Metas\uMetaFil.pas' {FrmMetaFil},
  uMetaSub in 'uniVendas\Metas\uMetaSub.pas' {FrmMetaSub},
  uMetasVen in 'uniVendas\Metas\uMetasVen.pas' {FrmMetaVen},
  uMetaVnd in 'uniVendas\Metas\uMetaVnd.pas' {FrmMetaVnd},
  uRecePOS in 'uniCaixa\uRecePOS.pas' {FrmRecePos},
  uDigReceita in 'uniVendas\Receitas\uDigReceita.pas' {FrmDigRecei},
  uReceitaA in 'uniVendas\Receitas\uReceitaA.pas' {FrmReceitaA},
  uReceitaAltLotEstoq in 'uniVendas\Receitas\uReceitaAltLotEstoq.pas' {FrmReceitaAltLotEstoq},
  uReceitaB in 'uniVendas\Receitas\uReceitaB.pas' {FrmReceitaB},
  uReceitaB2 in 'uniVendas\Receitas\uReceitaB2.pas' {FrmReceitaB2},
  uReceitaBase in 'uniVendas\Receitas\uReceitaBase.pas' {FrmReceitaBase},
  uReceitaC in 'uniVendas\Receitas\uReceitaC.pas' {FrmReceitaC},
  uReceitaC2 in 'uniVendas\Receitas\uReceitaC2.pas' {FrmReceitaC2},
  uSelPBM in 'uniVendas\uSelPBM.pas' {FrmSelPBM},
  uMenEstoq in 'uniEstoque\uMenEstoq.pas' {FrmMenEsto};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TDM, DM);
  (*
  FrmAutoUpdate := TFrmAutoUpdate.Create(Application);
  try
    FrmAutoUpdate.ShowModal;
  finally
    FrmAutoUpdate.Update;
    FrmAutoUpdate.Hide;
    FrmAutoUpdate.Free;
  end;
*)
  if not DM.DownNewVersao then
  begin
     Application.CreateForm(TFrmPrincipal, FrmPrincipal);
     Application.Run;
  end;

end.


